In [1]:
import json
import pandas as pd
from typing import List, Dict, Any

In [15]:
df_camp = pd.read_csv('CAMP3_data.csv')
print(df_camp.head(10))
print(len(df_camp))

                                          Source_URL Accession_ID  \
0  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...    CAMPSQ834
1  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...   CAMPSQ1091
2  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...   CAMPSQ1170
3  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...    CAMPSQ497
4  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...      CAMPSQ6
5  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...   CAMPSQ2153
6  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...    CAMPSQ665
7  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...   CAMPSQ1607
8  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...    CAMPSQ647
9  https://camp3.bicnirrh.res.in/seqDisp.php?id=C...    CAMPSQ651

            Title GenInfo Identifier  \
0     Microcin C7           75347354
1    Colutellin-A          223635095
2          E07LKK                NaN
3         Ascalin           51315827
4    Pleurostatin          109892826
5     Bacteriocin           82592653
6       Jellein-1           20138866
7  Demidefensin-3           71153732
8       Jellein-3           88909166
9      Alveolarin           90109840

                                             Source           Taxonomy  \
0                                  Escherichia coli           Bacteria
1      Colletotrichum dematium [Anthracnose fungus]              Fungi
2                               Synthetic construct                NaN
3             Allium cepa var. aggregatum [Shallot]      Viridiplantae
4            Pleurotus ostreatus  [oyster mushroom]              Fungi
5                Rhizobium leguminosarum bv. viciae           Bacteria
6                         Apis mellifera [Honeybee]  Animalia, Insects
7                   Macaca mulatta [Rhesus macaque]  Animalia, Mammals
8                         Apis mellifera [Honeybee]  Animalia, Insects
9  Polyporus alveolaris  [Hexagonal-pored polypore]              Fungi

  UniProt                  PDB    PubMed  Length  ...        Gram Nature  \
0  Q47505  3H5R,3H9G,3H9J,3H9Q   2861788       7  ...            Gram-ve
1  P86168                  NaN  18599825       7  ...                NaN
2     NaN                  NaN   7726486       7  ...  Gram+ve,  Gram-ve
3  P84071                  NaN  12126728       7  ...                NaN
4  P84866                  NaN  15941607       8  ...                NaN
5  P84703                  NaN       NaN       8  ...                NaN
6  O18330                  NaN  15203237       8  ...  Gram+ve,  Gram-ve
7  Q9GLR2                  NaN       NaN       9  ...                NaN
8  P84759                  NaN  15203237       9  ...  Gram+ve,  Gram-ve
9  P84760                  NaN  15165727       9  ...                NaN

                                              Target  \
0  E. coli , Klebsiella pneumoniae , Salmonella t...
1  S.sclerotiorum ( MIC = 32.4 microg/ml after 28...
2                                  S. aureus, E.coli
3  B.cinerea, HIV-1 reverse transcriptase ( IC50 ...
4  20 % growth inhibition F. oxysporum ( MIC = 15...
5                                                NaN
6  S. aureus ATCC 6535 ( MIC = 10 microg/ml), S. ...
7                                                NaN
8  S.aureus ( MIC = 30 microg/ml), S.saprophyticu...
9  F.cinera, F.oxysporum, M.arachidicola, P.piricola

                  Validated  \
0  Experimentally Validated
1  Experimentally Validated
2  Experimentally Validated
3  Experimentally Validated
4  Experimentally Validated
5  Experimentally Validated
6  Experimentally Validated
7                 Predicted
8  Experimentally Validated
9  Experimentally Validated

                                             Comment   AMP Family   Sequence  \
0  Inactive against Klebsiella oxytoca , Serratia...  Bacteriocin    MRTGNAN
1  Inactive against P.ultimum, T.viride and R.solani          NaN    VISIIPV
2                                                NaN          NaN    LKLLKKL
3                                                NaN          NaN    YQCGQGG
4                                                NaN          NaN   VRPYLVAF
5                                                NaN  Bacteriocin   ASILTNAS
6                                                NaN          NaN   PFKISIHL
7                                                NaN     Defensin  RCICVLGIC
8                                                NaN          NaN  EPFKISIHL
9                                                NaN          NaN  GVCDMADLA

                                  Hemolytic Activity  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4  48.6 +/- 3.2 % inhibition of rabbit reticulate...
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9                                                NaN

                                         Pfam  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6  PF03022:     ( Major royal jelly protein )
7        PF00879:     ( Defensin propeptide )
8                                         NaN
9                                         NaN

                                            InterPro Signature
0                                                NaN       NaN
1                                                NaN       NaN
2                                                NaN       NaN
3                                                NaN       NaN
4                                                NaN       NaN
5                                                NaN       NaN
6  IPR011042: 6-blade_b-propeller_TolB-like.IPR01...       NaN
7  IPR016327: Alpha-defensin.IPR002366: Defensin_...       NaN
8                                                NaN       NaN
9                                                NaN       NaN

[10 rows x 21 columns]
2226

In [ ]:
print(df_camp.columns)

Index(['Source_URL', 'Accession_ID', 'Title', 'GenInfo Identifier', 'Source',
       'Taxonomy', 'UniProt', 'PDB', 'PubMed', 'Length', 'Activity',
       'Gram Nature', 'Target', 'Validated', 'Comment', 'AMP Family',
       'Sequence', 'Hemolytic Activity', 'Pfam', 'InterPro', 'Signature'],
      dtype='object')

In [16]:
df_camp["Activity"] = df_camp["Activity"] + ", " + df_camp["Gram Nature"]
df_camp = df_camp[['Accession_ID', 'Sequence', 'Length', 'Activity', "Target", 'Hemolytic Activity']].copy()
# 清洗序列
def clean_sequence(seq: str) -> str:
    seq = seq.upper().strip()
    standard_aa = set("ACDEFGHIKLMNPQRSTVWY")
    if set(seq).issubset(standard_aa):
        return seq
    else:
        return None
df_camp["Sequence"] = df_camp["Sequence"].apply(clean_sequence)
df_camp = df_camp.dropna(subset=['Sequence'])
print(f"清洗完氨基酸序列后共有{len(df_camp)}条序列\n")

清洗完氨基酸序列后共有2182条序列

In [17]:

df_camp.head(10)

,Accession_ID,Sequence,Length,Activity,Target,Hemolytic Activity
0,CAMPSQ834,MRTGNAN,7,"Antibacterial, Gram-ve","E. coli , Klebsiella pneumoniae , Salmonella t...",NaN
1,CAMPSQ1091,VISIIPV,7,NaN,S.sclerotiorum ( MIC = 32.4 microg/ml after 28...,NaN
2,CAMPSQ1170,LKLLKKL,7,"Antibacterial, Gram+ve, Gram-ve","S. aureus, E.coli",NaN
3,CAMPSQ497,YQCGQGG,7,NaN,"B.cinerea, HIV-1 reverse transcriptase ( IC50 ...",NaN
4,CAMPSQ6,VRPYLVAF,8,NaN,20 % growth inhibition F. oxysporum ( MIC = 15...,48.6 +/- 3.2 % inhibition of rabbit reticulate...
5,CAMPSQ2153,ASILTNAS,8,NaN,NaN,NaN
6,CAMPSQ665,PFKISIHL,8,"Antibacterial, Antifungal, Gram+ve, Gram-ve","S. aureus ATCC 6535 ( MIC = 10 microg/ml), S. ...",NaN
7,CAMPSQ1607,RCICVLGIC,9,NaN,NaN,NaN
8,CAMPSQ647,EPFKISIHL,9,"Antibacterial, Gram+ve, Gram-ve","S.aureus ( MIC = 30 microg/ml), S.saprophyticu...",NaN
9,CAMPSQ651,GVCDMADLA,9,NaN,"F.cinera, F.oxysporum, M.arachidicola, P.piricola",NaN

In [18]:
df_camp.to_csv("CAMP3_cleaned.csv")

In [19]:
df_clean= pd.read_csv("CAMP3_cleaned.csv", encoding='utf-8')
df_clean.iloc[15]

Unnamed: 0                                                           15
Accession_ID                                                  CAMPSQ939
Sequence                                                      AWLLAIRKR
Length                                                                9
Activity                               Antibacterial, Gram+ve,  Gram-ve
Target                S. ?aureus ( MIC = 3 microg/ml), S. ?aureus MR...
Hemolytic Activity                                                  NaN
Name: 15, dtype: object

In [21]:
df_wide = pd.read_csv("CAMP3_wide_format.csv")
df_wide.head(10)

/tmp/ipykernel_1887823/1978233114.py:1: DtypeWarning: Columns (3,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,58,60,61,62,63,64,65,66,68,69,70,71,72,74,75,76,77,78,79,80,81,83,84,85,87,88,89,90,91,92,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,165,166,167,168,169,170,171,172,173,174,175,177,178,179,180,181,183,184,185,186,187,189,190,192,193,194,195,196,197,198,200,201,202,203,204,205,206,208,209,210,211,212,213,214,215,216,217,218,219,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,304,305,306,307,308,309,310,311,312,314,315,316,317,318,319,320,321,322,323,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,401,402,404,405,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,423,424,425,430,431,432,433,434,435,437,438,439,440,441,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,537,538,539,540,541,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,600,601,602,603,604,605,606,607,608,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,676,677,678,679,680,681,682,683,684,685,686,687,688,689,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,888,889,890,891,893,894,895,896,897,898,899,900,902,904,905,907,908,909,910,911,912,913,916,917,918,919,920,921,922,923,925,930,931,932,933,934,935,936,937,939,940,942,943,944,946,948,950,951,953,954,955,956,957,959,960,961,963,965,966) have mixed types. Specify dtype option on import or set low_memory=False.
  df_wide = pd.read_csv("CAMP3_wide_format.csv")

,Accession_ID,Sequence,Length,MIC(14028s parent of MS7953s),MIC(5CT),MIC(97?4),MIC(A. Hydrophila),MIC(A. brassicicola),MIC(A. brassicola),MIC(A. calcoaceticus Acl 1),...,IC50(Septoria nodorum),IC50(Septoria tritiei),IC50(Staphylococcus aureus),IC50(Staphylococcus aureus ATCC6538P),IC50(Trichoderma hamatum),IC50(Trichoderma viride),IC50(Venturia inaequalis),IC50(Verticiliium dahliae),IC50(Verticilium albo-atrum),IC50(Verticillium dahliae)
0,CAMPSQ834,MRTGNAN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAMPSQ1091,VISIIPV,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CAMPSQ1170,LKLLKKL,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CAMPSQ497,YQCGQGG,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CAMPSQ6,VRPYLVAF,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CAMPSQ2153,ASILTNAS,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CAMPSQ665,PFKISIHL,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,CAMPSQ1607,RCICVLGIC,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,CAMPSQ647,EPFKISIHL,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CAMPSQ651,GVCDMADLA,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
#ID,Sequence,Length,MIC_Value(ug/ml),Tax_ID,Raw_Species,Target_Species
# df_wide.drop(columns=["MIC(14028s parent of MS7953s)","MIC(5CT)","MIC(97?4)"],inplace=True)
df_wide.rename(columns={"Accession_ID": "ID"},inplace=True)
df_wide.head(10)

,ID,Sequence,Length,MIC(A. Hydrophila),MIC(A. brassicicola),MIC(A. brassicola),MIC(A. calcoaceticus Acl 1),MIC(A. calcoaceticus wt),MIC(A. flavus),MIC(A. fumigatus),...,IC50(Septoria nodorum),IC50(Septoria tritiei),IC50(Staphylococcus aureus),IC50(Staphylococcus aureus ATCC6538P),IC50(Trichoderma hamatum),IC50(Trichoderma viride),IC50(Venturia inaequalis),IC50(Verticiliium dahliae),IC50(Verticilium albo-atrum),IC50(Verticillium dahliae)
0,CAMPSQ834,MRTGNAN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAMPSQ1091,VISIIPV,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CAMPSQ1170,LKLLKKL,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CAMPSQ497,YQCGQGG,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CAMPSQ6,VRPYLVAF,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CAMPSQ2153,ASILTNAS,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CAMPSQ665,PFKISIHL,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,CAMPSQ1607,RCICVLGIC,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,CAMPSQ647,EPFKISIHL,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CAMPSQ651,GVCDMADLA,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df_wide.to_csv("CAMP3_wide_format.csv")

In [12]:
# 统计final_CAMP3_wide_format.csv 里面存在和缺失的数据
df_final_camp = pd.read_csv("final_CAMP3_wide_format.csv", dtype={"Tax_ID":str})
print(len(df_final_camp))
print(df_final_camp["Tax_ID"].value_counts())

2602
Tax_ID
562       358
1280      251
287       164
5476      120
1423       90
1282       61
1270       58
28901      53
1404       45
90371      37
615        31
4932       30
573        29
5507       22
1351       21
40559      20
1639       18
550        17
5207       16
1396       15
1642       14
303        12
584        12
1246       12
5518       10
1349        9
487         9
585         8
747         8
622         7
746128      7
1358        6
5141        6
1288        6
1665        6
1352        6
169388      6
1313        5
5516        5
36651       5
292         5
27337       5
92950       5
317         5
5061        4
160389      4
623         4
29385       4
548         4
1314        4
318829      4
5454        4
571         4
210         4
663         3
5551        3
37326       3
1283        3
483         3
5482        3
55601       3
1584        3
1377        3
648         3
61296       2
122368      2
624         2
1309        2
1281        2
290576      2
672         2
29497       2
523103      2
341027      2
1428        2
306         2
45151       2
261906      2
294         2
1718        2
5478        2
630         2
28447       2
40324       2
456999      2
546         2
485         1
1824        1
480         1
644         1
1311        1
459529      1
471         1
1363        1
1587        1
727         1
28037       1
552         1
82937       1
1685        1
1680        1
818         1
817         1
1408        1
1747        1
1502        1
1686        1
5059        1
38033       1
1509        1
29466       1
149539      1
33178       1
Name: count, dtype: int64

In [13]:
df_final_camp["Target_Species"].value_counts()

Target_Species
Escherichia coli                 358
Staphylococcus aureus            251
Pseudomonas aeruginosa           164
Candida albicans                 120
Bacillus subtilis                 90
Staphylococcus epidermidis        61
Micrococcus luteus                58
Salmonella enterica               53
Priestia megaterium               45
Salmonella typhimurium            37
Serratia marcescens               31
Saccharomyces cerevisiae          30
Klebsiella pneumoniae             29
Fusarium oxysporum                22
Enterococcus faecalis             21
Botrytis cinerea                  20
Listeria monocytogenes            18
Enterobacter cloacae              17
Cryptococcus neoformans           16
Bacillus cereus                   15
Listeria innocua                  14
Pseudomonas putida                12
Proteus mirabilis                 12
Leuconostoc lactis                12
Fusarium graminearum              10
Streptococcus uberis               9
Neisseria meningitidis             9
Proteus vulgaris                   8
Pasteurella multocida              8
Shigella dysenteriae               7
Aspergillus fumigatus              7
Lactococcus lactis                 6
Neurospora crassa                  6
Staphylococcus xylosus             6
Arthrobacter globiformis           6
Enterococcus faecium               6
Fusarium solani                    6
Streptococcus pneumoniae           5
Fusarium culmorum                  5
Penicillium digitatum              5
Burkholderia cepacia               5
Verticillium dahliae               5
Cladosporium sphaerospermum        5
Pseudomonas syringae               5
Aspergillus niger                  4
Alternaria longipes                4
Shigella flexneri                  4
Staphylococcus saprophyticus       4
Klebsiella aerogenes               4
Streptococcus pyogenes             4
Pyricularia oryzae                 4
Ascochyta rabiei                   4
Klebsiella oxytoca                 4
Helicobacter pylori                4
Vibrio alginolyticus               3
Trichophyton rubrum                3
Nocardia brasiliensis              3
Staphylococcus haemolyticus        3
Neisseria cinerea                  3
Candida tropicalis                 3
Vibrio anguillarum                 3
Lactobacillus delbrueckii          3
Aerococcus viridans                3
Aeromonas caviae                   3
Aureobasidium sp.                  2
Cercospora beticola                2
Shigella sonnei                    2
Streptococcus mutans               2
Staphylococcus carnosus            2
Colletotrichum lindemuthianum      2
Vibrio vulnificus                  2
Vibrio splendidus                  2
Trichophyton mentagrophytes        2
Sphingobacterium sp.               2
Bacillus thuringiensis             2
Pseudomonas sp.                    2
Pyrenophora tritici-repentis       2
Penicillium jensenii               2
Pseudomonas fluorescens            2
Corynebacterium glutamicum         2
Candida glabrata                   2
Yersinia enterocolitica            2
Clavibacter michiganensis          2
Stenotrophomonas maltophilia       2
Rhizoctonia solani                 2
Citrobacter freundii               2
Neisseria gonorrhoeae              1
Nocardia asteroides                1
Moraxella catarrhalis              1
Aeromonas hydrophila               1
Streptococcus agalactiae           1
Sphingobacterium siyangense        1
Acinetobacter calcoaceticus        1
Lactococcus garvieae               1
Lactobacillus helveticus           1
Haemophilus influenzae             1
Streptococcus mitis                1
Erwinia amylovora                  1
Pythium graminicola                1
Bifidobacterium breve              1
Bifidobacterium adolescentis       1
Bacteroides thetaiotaomicron       1
Bacteroides fragilis               1
Bacillus pumilus                   1
Propionibacterium acnes            1
Clostridium perfringens            1
Bifidobacterium catenulatum        1
Aspergillus flavus                 1
Chaetomium globosum                1
Clostridium sporogenes             1
Veillonella parvula                1
Salmonella enteritidis             1
Aspergillus terreus                1
Name: count, dtype: int64

In [14]:
# 统计Target_Species的不同物种数量
# 如果Target_Species是NaN，则使用Raw_Species的值

# 创建一个新的Series，用来处理NaN值
species_list = []
from_raw_species = set()  # 记录来自Raw_Species的物种

for idx, row in df_final_camp.iterrows():
    if pd.isna(row['Target_Species']):
        # 如果Target_Species是NaN，使用Raw_Species
        species = row['Raw_Species']
        from_raw_species.add(species)
    else:
        # 否则使用Target_Species
        species = row['Target_Species']
    species_list.append(species)

# 统计不同物种的数量
unique_species = pd.Series(species_list).value_counts()
print(f"总共有 {len(unique_species)} 种不同的物种\n")
print("=" * 80)
print("各物种的数量统计:")
print("=" * 80)

# 设置pandas显示选项，不省略输出
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

for species, count in unique_species.items():
    if species in from_raw_species:
        print(f"{species}: {count} (来自Raw_Species, Target_Species为NaN)")
    else:
        print(f"{species}: {count}")

print("=" * 80)
print(f"总条数: {len(species_list)}")
print(f"Target_Species为NaN的物种数: {len(from_raw_species)}")

总共有 437 种不同的物种

================================================================================
各物种的数量统计:
================================================================================
Escherichia coli: 358
Staphylococcus aureus: 251
Pseudomonas aeruginosa: 164
Candida albicans: 120
Bacillus subtilis: 90
Staphylococcus epidermidis: 61
Micrococcus luteus: 58
Salmonella enterica: 53
S.aureus: 50 (来自Raw_Species, Target_Species为NaN)
Priestia megaterium: 45
E.coli: 44 (来自Raw_Species, Target_Species为NaN)
A. salmonicida: 42 (来自Raw_Species, Target_Species为NaN)
Salmonella typhimurium: 37
Serratia marcescens: 31
Saccharomyces cerevisiae: 30
Klebsiella pneumoniae: 29
Fusarium oxysporum: 22
MRSA C623: 21 (来自Raw_Species, Target_Species为NaN)
Enterococcus faecalis: 21
E.coli ATCC: 20 (来自Raw_Species, Target_Species为NaN)
Botrytis cinerea: 20
P.aeruginosa: 19 (来自Raw_Species, Target_Species为NaN)
C.albicans: 18 (来自Raw_Species, Target_Species为NaN)
Listeria monocytogenes: 18
S.aureus ATCC: 18 (来自Raw_Species, Target_Species为NaN)
Enterobacter cloacae: 17
Cryptococcus neoformans: 16
Bacillus cereus: 15
Listeria innocua: 14
Pseudomonas putida: 12
S. pyogenes: 12 (来自Raw_Species, Target_Species为NaN)
Leuconostoc lactis: 12
F. culmorum: 12 (来自Raw_Species, Target_Species为NaN)
Proteus mirabilis: 12
P. freudenreichii: 11 (来自Raw_Species, Target_Species为NaN)
M.luteus: 11 (来自Raw_Species, Target_Species为NaN)
Fusarium graminearum: 10
Streptococcus uberis: 9
B.subtilis: 9 (来自Raw_Species, Target_Species为NaN)
Neisseria meningitidis: 9
Pasteurella multocida: 8
Proteus vulgaris: 8
L.lactis: 7 (来自Raw_Species, Target_Species为NaN)
Leptosphaeria maculans: 7 (来自Raw_Species, Target_Species为NaN)
Bacillus dysenteriae: 7 (来自Raw_Species, Target_Species为NaN)
Shigella dysenteriae: 7
Aspergillus fumigatus: 7
Staphylococcus xylosus: 6
C. difficile: 6 (来自Raw_Species, Target_Species为NaN)
Fusarium solani: 6
Neurospora crassa: 6
Arthrobacter globiformis: 6
Enterococcus faecium: 6
P. pastoris: 6 (来自Raw_Species, Target_Species为NaN)
S.uberis: 6 (来自Raw_Species, Target_Species为NaN)
Lactococcus lactis: 6
S.epidermidis: 6 (来自Raw_Species, Target_Species为NaN)
Pseudomonas syringae: 5
A. hydrophila: 5 (来自Raw_Species, Target_Species为NaN)
Streptococcus pneumoniae: 5
A. brassicola: 5 (来自Raw_Species, Target_Species为NaN)
Agrobacterium tumefaciens: 5 (来自Raw_Species, Target_Species为NaN)
Fusarium culmorum: 5
Burkholderia cepacia: 5
E.coli D21: 5 (来自Raw_Species, Target_Species为NaN)
Bacillus megatherium: 5 (来自Raw_Species, Target_Species为NaN)
Cladosporium sphaerospermum: 5
Penicillium digitatum: 5
N.crassa: 5 (来自Raw_Species, Target_Species为NaN)
Streptococcus faecalis: 5 (来自Raw_Species, Target_Species为NaN)
F. oxysporum: 5 (来自Raw_Species, Target_Species为NaN)
N.hematococca: 5 (来自Raw_Species, Target_Species为NaN)
P.aeruginosa ATCC15692: 5 (来自Raw_Species, Target_Species为NaN)
L.innocua: 5 (来自Raw_Species, Target_Species为NaN)
Verticillium dahliae: 5
F.culmorum: 4 (来自Raw_Species, Target_Species为NaN)
Pyricularia oryzae: 4
E.coli O157:H7: 4 (来自Raw_Species, Target_Species为NaN)
F.oxysporum: 4 (来自Raw_Species, Target_Species为NaN)
P.aeruginosa ATCC: 4 (来自Raw_Species, Target_Species为NaN)
F.oxyporum: 4 (来自Raw_Species, Target_Species为NaN)
Klebsiella aerogenes: 4
A. brassicicola: 4 (来自Raw_Species, Target_Species为NaN)
Ascochyta rabiei: 4
inhibition Neisseria: 4 (来自Raw_Species, Target_Species为NaN)
Alternaria longipes: 4
T. viride: 4 (来自Raw_Species, Target_Species为NaN)
Alternaria brassicola: 4 (来自Raw_Species, Target_Species为NaN)
Aspergillus niger: 4
Streptococcus pyogenes: 4
V. alboatrum: 4 (来自Raw_Species, Target_Species为NaN)
V. Alboatrum: 4 (来自Raw_Species, Target_Species为NaN)
Helicobacter pylori: 4
B.cinerea: 4 (来自Raw_Species, Target_Species为NaN)
Shigella flexneri: 4
B.megaterium: 4 (来自Raw_Species, Target_Species为NaN)
Staphylococcus saprophyticus: 4
S.aureus 1056: 4 (来自Raw_Species, Target_Species为NaN)
C. kefyr: 4 (来自Raw_Species, Target_Species为NaN)
Klebsiella oxytoca: 4
Propionibacterium acidipropionici: 3 (来自Raw_Species, Target_Species为NaN)
Aeromonas caviae: 3
Lactobacillus plantarum: 3 (来自Raw_Species, Target_Species为NaN)
Arthroderma simii: 3 (来自Raw_Species, Target_Species为NaN)
Vibrio anguillarum: 3
Vibrio alginolyticus: 3
Erwinia salicis: 3 (来自Raw_Species, Target_Species为NaN)
Neisseria cinerea: 3
Neisseria gonorrhoeoe: 3 (来自Raw_Species, Target_Species为NaN)
Nocardia brasiliensis: 3
Y. enterocolitica: 3 (来自Raw_Species, Target_Species为NaN)
Y. pseudotuberculosis: 3 (来自Raw_Species, Target_Species为NaN)
Microsporum canis: 3 (来自Raw_Species, Target_Species为NaN)
Lactobacillus delbrueckii: 3
C. parapsilosis: 3 (来自Raw_Species, Target_Species为NaN)
Candida tropicalis: 3
Aerococcus viridans: 3
B.megaterium Bm11: 3 (来自Raw_Species, Target_Species为NaN)
Salmonella Newport: 3 (来自Raw_Species, Target_Species为NaN)
S.saprophyticus: 3 (来自Raw_Species, Target_Species为NaN)
S.aureus Cowan: 3 (来自Raw_Species, Target_Species为NaN)
C. botulinum: 3 (来自Raw_Species, Target_Species为NaN)
Staphylococcus haemolyticus: 3
Streptococcus fecalis: 3 (来自Raw_Species, Target_Species为NaN)
Trichophyton rubrum: 3
Rhizobium meliloti: 3 (来自Raw_Species, Target_Species为NaN)
T.mentagrophytes: 3 (来自Raw_Species, Target_Species为NaN)
Corynebacterium insidiosum: 3 (来自Raw_Species, Target_Species为NaN)
[E. coli: 3 (来自Raw_Species, Target_Species为NaN)
A.fumigatus: 3 (来自Raw_Species, Target_Species为NaN)
A. flavus: 3 (来自Raw_Species, Target_Species为NaN)
Propionibacterium freudenreichii: 3 (来自Raw_Species, Target_Species为NaN)
[ Refer: 2 (来自Raw_Species, Target_Species为NaN)
Yersinia enterocolitica: 2
Staphylococcus carnosus: 2
Brucella suis: 2 (来自Raw_Species, Target_Species为NaN)
M. arachidicola: 2 (来自Raw_Species, Target_Species为NaN)
Bacillus thuringiensis: 2
B.subtilis ATCC: 2 (来自Raw_Species, Target_Species为NaN)
Methicillin resistant: 2 (来自Raw_Species, Target_Species为NaN)
Aureobasidium sp.: 2
A. calcoaceticus: 2 (来自Raw_Species, Target_Species为NaN)
B.subtilis CCT: 2 (来自Raw_Species, Target_Species为NaN)
B.cereus: 2 (来自Raw_Species, Target_Species为NaN)
Aeromonas salmonicida: 2 (来自Raw_Species, Target_Species为NaN)
[Salmonella typhimurium: 2 (来自Raw_Species, Target_Species为NaN)
Z61 supersusceptible: 2 (来自Raw_Species, Target_Species为NaN)
B. megateriurn: 2 (来自Raw_Species, Target_Species为NaN)
Trichophyton mentagrophytes: 2
Trypanosoma cruzi: 2 (来自Raw_Species, Target_Species为NaN)
Aspergillus versicolor: 2 (来自Raw_Species, Target_Species为NaN)
Streptococcus mutans: 2
Streptococcus pyogeneis: 2 (来自Raw_Species, Target_Species为NaN)
Streptococcus bovis: 2 (来自Raw_Species, Target_Species为NaN)
A. Hydrophila: 2 (来自Raw_Species, Target_Species为NaN)
Ascochyta pisi: 2 (来自Raw_Species, Target_Species为NaN)
UB1005 parent: 2 (来自Raw_Species, Target_Species为NaN)
Sphingobacterium sp.: 2
C. piscicola: 2 (来自Raw_Species, Target_Species为NaN)
Venturia inequalis: 2 (来自Raw_Species, Target_Species为NaN)
Shigella sonnei: 2
Xenorhabdus nematophilus: 2 (来自Raw_Species, Target_Species为NaN)
inhibitionNeisseria Iactamica: 2 (来自Raw_Species, Target_Species为NaN)
Vibrio vulnificus: 2
Vibrio splendidus: 2
Ureaplasma urealyticum: 2 (来自Raw_Species, Target_Species为NaN)
E.coli D31: 2 (来自Raw_Species, Target_Species为NaN)
Clavibacter michiganensis: 2
Enterococcus spp.: 2 (来自Raw_Species, Target_Species为NaN)
Clinical isolate: 2 (来自Raw_Species, Target_Species为NaN)
E.faecalis: 2 (来自Raw_Species, Target_Species为NaN)
E.coliD21: 2 (来自Raw_Species, Target_Species为NaN)
Colletotrichum lindemuthianum: 2
C.neoformans: 2 (来自Raw_Species, Target_Species为NaN)
Cercospora beticola: 2
Citrobacter freundii: 2
Sarcina lutea: 2 (来自Raw_Species, Target_Species为NaN)
Rhizoctonia solani: 2
Pseudomonas solanacearum: 2 (来自Raw_Species, Target_Species为NaN)
Fusarium moniliforme: 2 (来自Raw_Species, Target_Species为NaN)
Pyrenophora tritici-repentis: 2
Penicillium jensenii: 2
Propionibacterium thoenii: 2 (来自Raw_Species, Target_Species为NaN)
F.moniliforme: 2 (来自Raw_Species, Target_Species为NaN)
Pseudomonas sp.: 2
Phoma betae: 2 (来自Raw_Species, Target_Species为NaN)
Perkinsus marinus: 2 (来自Raw_Species, Target_Species为NaN)
Erwinia carotovora: 2 (来自Raw_Species, Target_Species为NaN)
C. divergens: 2 (来自Raw_Species, Target_Species为NaN)
Candida glabrata: 2
Corynebacterium glutamicum: 2
H. influenzae: 2 (来自Raw_Species, Target_Species为NaN)
Sclerotinia sclerotiorum: 2 (来自Raw_Species, Target_Species为NaN)
S.typhimurium: 2 (来自Raw_Species, Target_Species为NaN)
S.sclerotiorum: 2 (来自Raw_Species, Target_Species为NaN)
S.cerevisiae: 2 (来自Raw_Species, Target_Species为NaN)
S.aureus Cowan1: 2 (来自Raw_Species, Target_Species为NaN)
S. uberis: 2 (来自Raw_Species, Target_Species为NaN)
Pediococcus parvulus: 2 (来自Raw_Species, Target_Species为NaN)
L.monocytogenes: 2 (来自Raw_Species, Target_Species为NaN)
S.?aureus MRSA: 2 (来自Raw_Species, Target_Species为NaN)
Stenotrophomonas maltophilia: 2
S. prolificans: 2 (来自Raw_Species, Target_Species为NaN)
Pseudomonas fluorescens: 2
P. citreus: 2 (来自Raw_Species, Target_Species为NaN)
S. epider-: 2 (来自Raw_Species, Target_Species为NaN)
E.coli CCT: 2 (来自Raw_Species, Target_Species为NaN)
P. piricola: 2 (来自Raw_Species, Target_Species为NaN)
P.aeruginosa PAO1: 2 (来自Raw_Species, Target_Species为NaN)
Cytophaga aquatilis: 2 (来自Raw_Species, Target_Species为NaN)
S.?aureus: 2 (来自Raw_Species, Target_Species为NaN)
vancomycin-resistant Enterococci: 1 (来自Raw_Species, Target_Species为NaN)
A. salmoni-: 1 (来自Raw_Species, Target_Species为NaN)
Streptococcus group: 1 (来自Raw_Species, Target_Species为NaN)
Streptococcus mitis: 1
Streptococcus. pyogenes: 1 (来自Raw_Species, Target_Species为NaN)
T. beigelii: 1 (来自Raw_Species, Target_Species为NaN)
T.harzianum: 1 (来自Raw_Species, Target_Species为NaN)
TZ415: 1 (来自Raw_Species, Target_Species为NaN)
Trichoderma viride: 1 (来自Raw_Species, Target_Species为NaN)
A. pisi: 1 (来自Raw_Species, Target_Species为NaN)
Aspergillus flavus: 1
Aspergillus niculans: 1 (来自Raw_Species, Target_Species为NaN)
Aspergillus terreus: 1
B. longum: 1 (来自Raw_Species, Target_Species为NaN)
U.canigenitalium 51252: 1 (来自Raw_Species, Target_Species为NaN)
U.urealyticum 27619: 1 (来自Raw_Species, Target_Species为NaN)
Ureaplasma canigenitalium: 1 (来自Raw_Species, Target_Species为NaN)
V. dahliae: 1 (来自Raw_Species, Target_Species为NaN)
V.anguillarum: 1 (来自Raw_Species, Target_Species为NaN)
Veillonella parvula: 1
Verticilium albo-atrum: 1 (来自Raw_Species, Target_Species为NaN)
Verticilium dahliae: 1 (来自Raw_Species, Target_Species为NaN)
Vibrio cholera: 1 (来自Raw_Species, Target_Species为NaN)
X. Oryzae: 1 (来自Raw_Species, Target_Species为NaN)
X. campestris: 1 (来自Raw_Species, Target_Species为NaN)
Xantbmonas oryzae: 1 (来自Raw_Species, Target_Species为NaN)
Xenorhabdus japonicus: 1 (来自Raw_Species, Target_Species为NaN)
Y.pseudotuberculosis YP: 1 (来自Raw_Species, Target_Species为NaN)
Yersinia pseudotubercolosis: 1 (来自Raw_Species, Target_Species为NaN)
Yersinia rukeri: 1 (来自Raw_Species, Target_Species为NaN)
[Aeromonas salmonicida: 1 (来自Raw_Species, Target_Species为NaN)
Lactococcus garvieae: 1
Leucothrix mucor: 1 (来自Raw_Species, Target_Species为NaN)
Listeria monocytogenes7973: 1 (来自Raw_Species, Target_Species为NaN)
M.arachidicola: 1 (来自Raw_Species, Target_Species为NaN)
M.catarrhalis: 1 (来自Raw_Species, Target_Species为NaN)
M.luteus ATCC4698: 1 (来自Raw_Species, Target_Species为NaN)
M.luteus KCTC: 1 (来自Raw_Species, Target_Species为NaN)
Macrophomina phaseolina: 1 (来自Raw_Species, Target_Species为NaN)
Moraxella catarrhalis: 1
Mycobacterium smegmatis: 1 (来自Raw_Species, Target_Species为NaN)
Mycoplasma humenis: 1 (来自Raw_Species, Target_Species为NaN)
Mycosphaerella arachidicola: 1 (来自Raw_Species, Target_Species为NaN)
Nocardia asteroides: 1
N. gonorrhea: 1 (来自Raw_Species, Target_Species为NaN)
N.gonorrhoeae 10150: 1 (来自Raw_Species, Target_Species为NaN)
Neisseria gonorrhoeae: 1
P. betae: 1 (来自Raw_Species, Target_Species为NaN)
Gallinarum biovar: 1 (来自Raw_Species, Target_Species为NaN)
Gloeosporium album: 1 (来自Raw_Species, Target_Species为NaN)
Group A: 1 (来自Raw_Species, Target_Species为NaN)
HIV-1: 1 (来自Raw_Species, Target_Species为NaN)
Haemophilus influenzae: 1
Influenzae virus: 1 (来自Raw_Species, Target_Species为NaN)
K.pneumonia ATCC: 1 (来自Raw_Species, Target_Species为NaN)
K.pneumoniae: 1 (来自Raw_Species, Target_Species为NaN)
K.pneumoniae 10031: 1 (来自Raw_Species, Target_Species为NaN)
KST740ak: 1 (来自Raw_Species, Target_Species为NaN)
KSTSi 6P: 1 (来自Raw_Species, Target_Species为NaN)
Klebsiella sp.: 1 (来自Raw_Species, Target_Species为NaN)
L.curvatus: 1 (来自Raw_Species, Target_Species为NaN)
L.fermentum: 1 (来自Raw_Species, Target_Species为NaN)
L.lactis BB24: 1 (来自Raw_Species, Target_Species为NaN)
L.monocytogenes 19115: 1 (来自Raw_Species, Target_Species为NaN)
L.sake: 1 (来自Raw_Species, Target_Species为NaN)
Lactobacillus helveticus: 1
Lactobacillus sakei: 1 (来自Raw_Species, Target_Species为NaN)
P. crustosum: 1 (来自Raw_Species, Target_Species为NaN)
P. nicotianae: 1 (来自Raw_Species, Target_Species为NaN)
P. oryzae: 1 (来自Raw_Species, Target_Species为NaN)
P. solanacearum: 1 (来自Raw_Species, Target_Species为NaN)
P. stipitis: 1 (来自Raw_Species, Target_Species为NaN)
P. tritici-repentis: 1 (来自Raw_Species, Target_Species为NaN)
P.aeruginosa 08031014: 1 (来自Raw_Species, Target_Species为NaN)
P.aeruginosa 08031205: 1 (来自Raw_Species, Target_Species为NaN)
P.aeruginosa CIP: 1 (来自Raw_Species, Target_Species为NaN)
P.aeruginosaATCC15692: 1 (来自Raw_Species, Target_Species为NaN)
P.fluorescens VKM: 1 (来自Raw_Species, Target_Species为NaN)
P.multocida: 1 (来自Raw_Species, Target_Species为NaN)
P.nicotianae spores: 1 (来自Raw_Species, Target_Species为NaN)
P.pntosaceus FBB61: 1 (来自Raw_Species, Target_Species为NaN)
P.pntosaceus FBB63: 1 (来自Raw_Species, Target_Species为NaN)
P.syringae pv: 1 (来自Raw_Species, Target_Species为NaN)
P2101: 1 (来自Raw_Species, Target_Species为NaN)
Pasteurella haemolytica: 1 (来自Raw_Species, Target_Species为NaN)
Pediococcus acidalactici: 1 (来自Raw_Species, Target_Species为NaN)
E.coli DH5-alpha: 1 (来自Raw_Species, Target_Species为NaN)
E.coli DH5alpha: 1 (来自Raw_Species, Target_Species为NaN)
E.coli JM109: 1 (来自Raw_Species, Target_Species为NaN)
E.coli K12-594: 1 (来自Raw_Species, Target_Species为NaN)
E.coli MH1: 1 (来自Raw_Species, Target_Species为NaN)
E.coli ML35: 1 (来自Raw_Species, Target_Species为NaN)
EL4 T-lymphoma: 1 (来自Raw_Species, Target_Species为NaN)
Edwardsiella ictaluri: 1 (来自Raw_Species, Target_Species为NaN)
Erwinia amylovora: 1
Escherichia coliATCC25922: 1 (来自Raw_Species, Target_Species为NaN)
Eubacterium contortum: 1 (来自Raw_Species, Target_Species为NaN)
F. moniliforme: 1 (来自Raw_Species, Target_Species为NaN)
Penicillium uticale: 1 (来自Raw_Species, Target_Species为NaN)
Physalospora piricola: 1 (来自Raw_Species, Target_Species为NaN)
Pichia pastoris: 1 (来自Raw_Species, Target_Species为NaN)
Pr.vulgaris: 1 (来自Raw_Species, Target_Species为NaN)
Propionibacterium acnes: 1
Proteus.vulgaris: 1 (来自Raw_Species, Target_Species为NaN)
Providencia stuartii: 1 (来自Raw_Species, Target_Species为NaN)
Ps.aeruginosa OT97: 1 (来自Raw_Species, Target_Species为NaN)
Pseudomonas lachrymans: 1 (来自Raw_Species, Target_Species为NaN)
Pseudomonas luteola: 1 (来自Raw_Species, Target_Species为NaN)
Pythium graminicola: 1
R. gnavus: 1 (来自Raw_Species, Target_Species为NaN)
R. meliloti: 1 (来自Raw_Species, Target_Species为NaN)
R. torques: 1 (来自Raw_Species, Target_Species为NaN)
Rhizoctonia cerealis: 1 (来自Raw_Species, Target_Species为NaN)
Ruminococcus obeum: 1 (来自Raw_Species, Target_Species为NaN)
C.perfringes: 1 (来自Raw_Species, Target_Species为NaN)
C.tropicalis: 1 (来自Raw_Species, Target_Species为NaN)
C.tropicalis KCTC: 1 (来自Raw_Species, Target_Species为NaN)
Ceratocystis parodoxa: 1 (来自Raw_Species, Target_Species为NaN)
Chaetomium globosum: 1
Clostridium difficile: 1 (来自Raw_Species, Target_Species为NaN)
Clostridium sporogenes: 1
Corynebacterium bouis: 1 (来自Raw_Species, Target_Species为NaN)
Corynebacterium group: 1 (来自Raw_Species, Target_Species为NaN)
Corynebacterium michiganense: 1 (来自Raw_Species, Target_Species为NaN)
DR): 1 (来自Raw_Species, Target_Species为NaN)
E.coli 0111: 1 (来自Raw_Species, Target_Species为NaN)
E.coli 25922: 1 (来自Raw_Species, Target_Species为NaN)
E.coli 54127: 1 (来自Raw_Species, Target_Species为NaN)
E.coli 700336: 1 (来自Raw_Species, Target_Species为NaN)
E.coli C600: 1 (来自Raw_Species, Target_Species为NaN)
S. epider: 1 (来自Raw_Species, Target_Species为NaN)
S. flexneri: 1 (来自Raw_Species, Target_Species为NaN)
S. lentus: 1 (来自Raw_Species, Target_Species为NaN)
S. lutea: 1 (来自Raw_Species, Target_Species为NaN)
S. melliferum: 1 (来自Raw_Species, Target_Species为NaN)
S. newport: 1 (来自Raw_Species, Target_Species为NaN)
S. pyogenes/3: 1 (来自Raw_Species, Target_Species为NaN)
S. simulans: 1 (来自Raw_Species, Target_Species为NaN)
S.aureus 10832: 1 (来自Raw_Species, Target_Species为NaN)
S.aureus CCT: 1 (来自Raw_Species, Target_Species为NaN)
S.aureus FDA209P: 1 (来自Raw_Species, Target_Species为NaN)
S.aureus KCTC: 1 (来自Raw_Species, Target_Species为NaN)
S.aureus MRSA: 1 (来自Raw_Species, Target_Species为NaN)
S.aureus NCTC: 1 (来自Raw_Species, Target_Species为NaN)
S.carnosus TM300: 1 (来自Raw_Species, Target_Species为NaN)
S.cerevisiae Y190: 1 (来自Raw_Species, Target_Species为NaN)
S.epidermidis CS: 1 (来自Raw_Species, Target_Species为NaN)
S.epidermidis5: 1 (来自Raw_Species, Target_Species为NaN)
S.lentus: 1 (来自Raw_Species, Target_Species为NaN)
S.lutea: 1 (来自Raw_Species, Target_Species为NaN)
S.marcescens: 1 (来自Raw_Species, Target_Species为NaN)
S.michiganensis subspecies: 1 (来自Raw_Species, Target_Species为NaN)
S.pneumoniae: 1 (来自Raw_Species, Target_Species为NaN)
S.saprophyticus CS: 1 (来自Raw_Species, Target_Species为NaN)
S.simulans 22: 1 (来自Raw_Species, Target_Species为NaN)
S.sonnei: 1 (来自Raw_Species, Target_Species为NaN)
S.typhimurium ATCC: 1 (来自Raw_Species, Target_Species为NaN)
Sacharibacillus kuerlensis: 1 (来自Raw_Species, Target_Species为NaN)
Salmonella Enteritidis: 1 (来自Raw_Species, Target_Species为NaN)
Salmonella Typhimurium: 1 (来自Raw_Species, Target_Species为NaN)
Salmonella arizonae: 1 (来自Raw_Species, Target_Species为NaN)
Salmonella enteritidis: 1
Salmonella newport: 1 (来自Raw_Species, Target_Species为NaN)
Salmonella typhymurium: 1 (来自Raw_Species, Target_Species为NaN)
Septoria tritiei: 1 (来自Raw_Species, Target_Species为NaN)
C. freundii: 1 (来自Raw_Species, Target_Species为NaN)
C. guillermondii: 1 (来自Raw_Species, Target_Species为NaN)
C. jejuni: 1 (来自Raw_Species, Target_Species为NaN)
C. lindemuthianum: 1 (来自Raw_Species, Target_Species为NaN)
C. nexile: 1 (来自Raw_Species, Target_Species为NaN)
C. oroticum: 1 (来自Raw_Species, Target_Species为NaN)
Clostridium perfringens: 1
C. septicum: 1 (来自Raw_Species, Target_Species为NaN)
C. sordellii: 1 (来自Raw_Species, Target_Species为NaN)
C. sporogenes: 1 (来自Raw_Species, Target_Species为NaN)
C. wickerhamii: 1 (来自Raw_Species, Target_Species为NaN)
C.ablicans: 1 (来自Raw_Species, Target_Species为NaN)
C.albicans 11006: 1 (来自Raw_Species, Target_Species为NaN)
C.albicans 14053: 1 (来自Raw_Species, Target_Species为NaN)
C.albicans 3153A: 1 (来自Raw_Species, Target_Species为NaN)
C.albicans ATCC: 1 (来自Raw_Species, Target_Species为NaN)
C.albicans KCTC: 1 (来自Raw_Species, Target_Species为NaN)
C.botulinum: 1 (来自Raw_Species, Target_Species为NaN)
C.glabrata: 1 (来自Raw_Species, Target_Species为NaN)
C.gossypi: 1 (来自Raw_Species, Target_Species为NaN)
C.gossypii: 1 (来自Raw_Species, Target_Species为NaN)
C.guiller-mondii: 1 (来自Raw_Species, Target_Species为NaN)
B. megaterrum: 1 (来自Raw_Species, Target_Species为NaN)
B. thuringiensis: 1 (来自Raw_Species, Target_Species为NaN)
B.megaterium BmII: 1 (来自Raw_Species, Target_Species为NaN)
B.megaterium local: 1 (来自Raw_Species, Target_Species为NaN)
B.subtilis KCTC: 1 (来自Raw_Species, Target_Species为NaN)
B.subtilis VKM: 1 (来自Raw_Species, Target_Species为NaN)
B.thuringiensis: 1 (来自Raw_Species, Target_Species为NaN)
Bacillus megateriun: 1 (来自Raw_Species, Target_Species为NaN)
Bacillus pumilus: 1
Bacteroides fragilis: 1
Bacteroides thetaiotaomicron: 1
Bacteroides vulgatus: 1 (来自Raw_Species, Target_Species为NaN)
Bifidobacterium adolescentis: 1
Bifidobacterium breve: 1
Bifidobacterium catenulatum: 1
C. bifermentans: 1 (来自Raw_Species, Target_Species为NaN)
Sphingobacterium siyangense: 1
Staphylococcus saprophiticus: 1 (来自Raw_Species, Target_Species为NaN)
Staphylococcus smith: 1 (来自Raw_Species, Target_Species为NaN)
Strain 122: 1 (来自Raw_Species, Target_Species为NaN)
Strepococcus faecalis: 1 (来自Raw_Species, Target_Species为NaN)

In [15]:
df2 = df_final_camp[df_final_camp["Target_Species"].isna()].copy()
print(len(df2))
print(df2.head(5))

826
           ID                        Sequence  Length  MIC_Value(ug/ml)  \
0   CAMPSQ207         FFHHIFRGIVHVGKTIHRLVTGG      23              20.0
1   CAMPSQ209         FFHHIFRGIVHVGRTIHRLVTGG      23              20.0
2  CAMPSQ1063                  RILSILRHQNLLKE      14              10.0
3  CAMPSQ1066        RILSILRHQNLLKELQDLALQGAK      24              10.0
4  CAMPSQ1065  TLRGDERILSILRHQNLLKELQDLALQGAK      30               7.0

  Tax_ID      Raw_Species Target_Species Strain
0    NaN    A. Hydrophila            NaN    NaN
1    NaN    A. Hydrophila            NaN    NaN
2    NaN  A. brassicicola            NaN    NaN
3    NaN  A. brassicicola            NaN    NaN
4    NaN  A. brassicicola            NaN    NaN

In [9]:
df2["Raw_Species"].value_counts()

Raw_Species
S.aureus                             50
E.coli                               44
A. salmonicida                       42
MRSA C623                            21
E.coli ATCC                          20
P.aeruginosa                         19
S.aureus ATCC                        18
C.albicans                           18
F. culmorum                          12
S. pyogenes                          12
P. freudenreichii                    11
M.luteus                             11
B.subtilis                            9
Bacillus dysenteriae                  7
Leptosphaeria maculans                7
L.lactis                              7
S.uberis                              6
C. difficile                          6
P. pastoris                           6
S.epidermidis                         6
A. brassicola                         5
E.coli D21                            5
Bacillus megatherium                  5
F. oxysporum                          5
L.innocua                             5
A. hydrophila                         5
P.aeruginosa ATCC15692                5
Agrobacterium tumefaciens             5
N.hematococca                         5
N.crassa                              5
Streptococcus faecalis                5
C. kefyr                              4
A. brassicicola                       4
P.aeruginosa ATCC                     4
Alternaria brassicola                 4
V. alboatrum                          4
E.coli O157:H7                        4
inhibition Neisseria                  4
T. viride                             4
F.culmorum                            4
S.aureus 1056                         4
B.cinerea                             4
F.oxysporum                           4
V. Alboatrum                          4
B.megaterium                          4
F.oxyporum                            4
Salmonella Newport                    3
Streptococcus fecalis                 3
C. botulinum                          3
C. parapsilosis                       3
T.mentagrophytes                      3
A.fumigatus                           3
Propionibacterium freudenreichii      3
Propionibacterium acidipropionici     3
Rhizobium meliloti                    3
S.aureus Cowan                        3
Lactobacillus plantarum               3
Microsporum canis                     3
Corynebacterium insidiosum            3
Neisseria gonorrhoeoe                 3
Arthroderma simii                     3
S.saprophyticus                       3
Erwinia salicis                       3
B.megaterium Bm11                     3
Y. enterocolitica                     3
[E. coli                              3
Y. pseudotuberculosis                 3
A. flavus                             3
L.monocytogenes                       2
S.sclerotiorum                        2
H. influenzae                         2
B.subtilis CCT                        2
Fusarium moniliforme                  2
F.moniliforme                         2
Erwinia carotovora                    2
Enterococcus spp.                     2
Xenorhabdus nematophilus              2
E.faecalis                            2
E.coliD21                             2
C. divergens                          2
E.coli D31                            2
E.coli CCT                            2
C. piscicola                          2
[Salmonella typhimurium               2
[ Refer                               2
Z61 supersusceptible                  2
Brucella suis                         2
P.aeruginosa PAO1                     2
P. piricola                           2
Pediococcus parvulus                  2
P. citreus                            2
Perkinsus marinus                     2
Phoma betae                           2
Propionibacterium thoenii             2
Cytophaga aquatilis                   2
Pseudomonas solanacearum              2
S.cerevisiae                          2
C.neoformans                          2
S. epider-                            2
S. prolificans                        2
S. uberis                             2
S.?aureus                             2
S.?aureus MRSA                        2
Methicillin resistant                 2
S.aureus Cowan1                       2
M. arachidicola                       2
Clinical isolate                      2
Ascochyta pisi                        2
Streptococcus bovis                   2
Aspergillus versicolor                2
Aeromonas salmonicida                 2
B.subtilis ATCC                       2
B. megateriurn                        2
Streptococcus pyogeneis               2
B.cereus                              2
Trypanosoma cruzi                     2
UB1005 parent                         2
Sarcina lutea                         2
Ureaplasma urealyticum                2
Venturia inequalis                    2
inhibitionNeisseria Iactamica         2
Sclerotinia sclerotiorum              2
A. calcoaceticus                      2
S.typhimurium                         2
A. Hydrophila                         2
R. meliloti                           1
R. torques                            1
Rhizoctonia cerealis                  1
Ruminococcus obeum                    1
P.multocida                           1
P.syringae pv                         1
S. epider                             1
Streptococcus group                   1
S. flexneri                           1
S. lutea                              1
S. melliferum                         1
P.pntosaceus FBB63                    1
S. newport                            1
Streptococcus equisimilis             1
S. pyogenes/3                         1
S. simulans                           1
P.nicotianae spores                   1
P.pntosaceus FBB61                    1
S. lentus                             1
Penicillium uticale                   1
Trichoderma viride                    1
Physalospora piricola                 1
mollicutes                            1
Pichia pastoris                       1
Pr.vulgaris                           1
TZ415                                 1
vancomycin-resistant Enterococci      1
Proteus.vulgaris                      1
Streptococcus. pyogenes               1
Pasteurella haemolytica               1
Providencia stuartii                  1
Ps.aeruginosa OT97                    1
T.harzianum                           1
Strepococcus faecalis                 1
Pseudomonas lachrymans                1
Pseudomonas luteola                   1
T. beigelii                           1
P2101                                 1
R. gnavus                             1
Pediococcus acidalactici              1
B.thuringiensis                       1
Bacillus megateriun                   1
Bacteroides vulgatus                  1
Salmonella typhymurium                1
Salmonella newport                    1
C. bifermentans                       1
C. freundii                           1
C. guillermondii                      1
C. jejuni                             1
C. lindemuthianum                     1
S.aureus KCTC                         1
Salmonella Typhimurium                1
C. nexile                             1
C. oroticum                           1
Salmonella Enteritidis                1
Sacharibacillus kuerlensis            1
C. septicum                           1
S.typhimurium ATCC                    1
C. sordellii                          1
C. sporogenes                         1
S.simulans 22                         1
S.sonnei                              1
Salmonella arizonae                   1
S.aureus 10832                        1
S.aureus CCT                          1
S.aureus FDA209P                      1
Strain 122                            1
S.aureus MRSA                         1
S.aureus NCTC                         1
S.carnosus TM300                      1
S.cerevisiae Y190                     1
Staphylococcus smith                  1
S.epidermidis CS                      1
S.epidermidis5                        1
B.subtilis VKM                        1
S.lutea                               1
S.marcescens                          1
S.michiganensis subspecies            1
S.pneumoniae                          1
S.saprophyticus CS                    1
Staphylococcus saprophiticus          1
B.megaterium BmII                     1
B.megaterium local                    1
P.fluorescens VKM                     1
B.subtilis KCTC                       1
Septoria tritiei                      1
S.lentus                              1
Y.pseudotuberculosis YP               1
Yersinia pseudotubercolosis           1
Yersinia rukeri                       1
[Aeromonas salmonicida                1
firmicutes                            1
gracilicutes                          1
E.coli C600                           1
E.coli DH5-alpha                      1
E.coli DH5alpha                       1
E.coli JM109                          1
E.coli K12-594                        1
E.coli MH1                            1
E.coli ML35                           1
tyrobutyricum 1754                    1
Edwardsiella ictaluri                 1
Escherichia coliATCC25922             1
Eubacterium contortum                 1
F. moniliforme                        1
Gallinarum biovar                     1
Gloeosporium album                    1
Group A                               1
HIV-1                                 1
Influenzae virus                      1
K.pneumonia ATCC                      1
K.pneumoniae                          1
K.pneumoniae 10031                    1
KST740ak                              1
EL4 T-lymphoma                        1
A. globiformisVKM                     1
A. laidlawii                          1
A. lycopersici                        1
A. pisi                               1
A. salmoni-                           1
A.calcoaceticus                       1
A.faecalis ATCC                       1
A.lycopersici                         1
A.niger                               1
A.salmonicida subsp                   1
A.tumefaciens                         1
Alternaria brassicae                  1
Aspergillus niculans                  1
Xenorhabdus japonicus                 1
B. megaterrum                         1
B. thuringiensis                      1
U.canigenitalium 51252                1
U.urealyticum 27619                   1
Ureaplasma canigenitalium             1
V. dahliae                            1
V.anguillarum                         1
Verticilium albo-atrum                1
Verticilium dahliae                   1
Vibrio cholera                        1
X. Oryzae                             1
X. campestris                         1
Xantbmonas oryzae                     1
B. longum                             1
C.tropicalis                          1
C.tropicalis KCTC                     1
Ceratocystis parodoxa                 1
Clostridium difficile                 1
Corynebacterium bouis                 1
Corynebacterium group                 1
Corynebacterium michiganense          1
DR)                                   1
E.coli 0111                           1
E.coli 25922                          1
E.coli 54127                          1
E.coli 700336                         1
Mycoplasma humenis                    1
KSTSi 6P                              1
N. gonorrhea                          1
N.gonorrhoeae 10150                   1
P. betae                              1
P. crustosum                          1
P. nicotianae                         1
P. oryzae                             1
P. solanacearum                       1
P. stipitis                           1
P. tritici-repentis                   1
P.aeruginosa 08031014                 1
P.aeruginosa 08031205                 1
P.aeruginosa CIP                      1
P.aeruginosaATCC15692                 1
Mycosphaerella arachidicola           1
Klebsiella sp.                        1
L.curvatus                            1
L.fermentum                           1
L.lactis BB24                         1
L.monocytogenes 19115                 1
L.sake                                1
Lactobacillus sakei                   1
Leucothrix mucor                      1
Listeria monocytogenes7973            1
M.arachidicola                        1
M.catarrhalis                         1
M.luteus ATCC4698                     1
M.luteus KCTC                         1
C.perfringes                          1
Mycobacterium smegmatis               1
C. wickerhamii                        1
C.ablicans                            1
C.albicans 11006                      1
C.albicans 14053                      1
C.albicans 3153A                      1
C.albicans ATCC                       1
C.albicans KCTC                       1
C.botulinum                           1
C.glabrata                            1
C.gossypi                             1
C.gossypii                            1
C.guiller-mondii                      1
Macrophomina phaseolina               1
Name: count, dtype: int64

In [10]:
raw_species = "E.coli 0111"
parts = raw_species.split()
if "." in parts[0] and parts[0][-1] != ".":
        # E.coli 0111
        species_parts = parts[0].split(".")
        species_part = ". ".join(species_parts)
        strain_part = " ".join(parts[1:])
        print(species_part, strain_part)

E. coli 0111

In [16]:
df1 = df_final_camp[~df_final_camp["Target_Species"].isna()].copy()
print(len(df1))
print(df1.head(5))
df2.to_csv("CAMP3_2.csv")
df1.to_csv("CAMP3_1.csv")

1776
           ID                  Sequence  Length  MIC_Value(ug/ml)  Tax_ID  \
16  CAMPSQ281       AKKVFKRLEKLFSKIQNDK      19              50.0  746128
17  CAMPSQ373    FFHHIFRGIVHVGKTIHKLVTG      22              50.0  746128
18   CAMPSQ45      SWKSMAKKLKEYMEKLKQRA      20               0.3    1665
19   CAMPSQ46      SWASMAKKLKEYMEKLKQRA      20               0.7    1665
20   CAMPSQ47  SLKDKVKSMGEKLKQYIQTWKAKF      24               0.3    1665

       Raw_Species            Target_Species       Strain
16    A. fumigatus     Aspergillus fumigatus          NaN
17    A. fumigatus     Aspergillus fumigatus          NaN
18  A. globiformis  Arthrobacter globiformis  VKM Ac-1112
19  A. globiformis  Arthrobacter globiformis  VKM Ac-1112
20  A. globiformis  Arthrobacter globiformis  VKM Ac-1112

In [19]:
df_camp2 = pd.read_csv("final_CAMP3_2.csv", dtype={"Tax_ID":str})
print(len(df_camp2))

826

In [20]:
df_camp2["Target_Species"].value_counts()

Target_Species
Escherichia coli                    88
Staphylococcus aureus               87
Pseudomonas aeruginosa              34
Candida albicans                    24
Fusarium culmorum                   16
Bacillus subtilis                   15
Propionibacterium freudenreichii    14
Micrococcus luteus                  13
Streptococcus pyogenes              13
Priestia megaterium                  9
Fusarium oxysporum                   9
Lactococcus lactis                   8
Staphylococcus epidermidis           8
Streptococcus uberis                 8
Staphylococcus faecalis              6
Listeria innocua                     5
Neurospora crassa                    5
Agrobacterium tumefaciens            5
Botrytis cinerea                     4
Staphylococcus saprophyticus         4
Clostridium botulinum                4
Candida parapsilosis                 3
Saccharomyces cerevisiae             3
Aspergillus fumigatus                3
Trichophyton mentagrophytes          3
Aspergillus flavus                   3
Acinetobacter calcoaceticus          3
Aeromonas salmonicida                3
Salmonella typhimurium               3
Listeria monocytogenes               3
Klebsiella pneumoniae                3
Microsporum canis                    3
Brucella suis                        2
Aspergillus versicolor               2
Bacillus thuringiensis               2
Ascochyta pisi                       2
Bacillus cereus                      2
Staphylococcus simulans              2
Candida tropicalis                   2
Enterococcus faecalis                2
Perkinsus marinus                    2
Cryptococcus neoformans              2
Pediococcus parvulus                 2
Proteus vulgaris                     2
Sclerotinia sclerotiorum             2
Ureaplasma urealyticum               2
Trypanosoma cruzi                    2
Acinetobacter faecalis               1
Aspergillus niger                    1
Alternaria brassicae                 1
Trichoderma viride                   1
Ureaplasma canigenitalium            1
Penicillium crustosum                1
Pseudomonas oryzae                   1
Pseudomonas fluorescens              1
Pasteurella multocida                1
Pseudomonas syringae                 1
Pseudomonas haemolytica              1
Leucothrix mucor                     1
Macrophomina phaseolina              1
Edwardsiella ictaluri                1
Klebsiella sp.                       1
Providencia stuartii                 1
Pseudomonas luteola                  1
Clostridium septicum                 1
Clostridium sporogenes               1
Candida glabrata                     1
Clostridium perfringens              1
Staphylococcus carnosus              1
Serratia marcescens                  1
Streptococcus pneumoniae             1
Shigella sonnei                      1
Vibrio anguillarum                   1
Name: count, dtype: int64

In [24]:
df_camp2.dropna(subset=["Target_Species"], inplace=True)
df_camp2["Target_Species"].isna().sum()

0

In [25]:
# 合并df1和df_camp2
df_final = pd.concat([df1, df_camp2], ignore_index=True)
print(f"df1行数: {len(df1)}")
print(f"df_camp2行数: {len(df_camp2)}")
print(f"合并后行数: {len(df_final)}")
print(f"\n合并后数据的列: {df_final.columns.tolist()}")
print(f"\n合并后数据前5行:")
print(df_final.head())

# 保存到final_CAMP3_MIC_processed.csv
df_final.to_csv("final_CAMP3_MIC_processed.csv", index=False)
print(f"\n已保存到 final_CAMP3_MIC_processed.csv")

df1行数: 1776
df_camp2行数: 468
合并后行数: 2244

合并后数据的列: ['ID', 'Sequence', 'Length', 'MIC_Value(ug/ml)', 'Tax_ID', 'Raw_Species', 'Target_Species', 'Strain']

合并后数据前5行:
          ID                  Sequence  Length  MIC_Value(ug/ml)  Tax_ID  \
0  CAMPSQ281       AKKVFKRLEKLFSKIQNDK      19              50.0  746128
1  CAMPSQ373    FFHHIFRGIVHVGKTIHKLVTG      22              50.0  746128
2   CAMPSQ45      SWKSMAKKLKEYMEKLKQRA      20               0.3    1665
3   CAMPSQ46      SWASMAKKLKEYMEKLKQRA      20               0.7    1665
4   CAMPSQ47  SLKDKVKSMGEKLKQYIQTWKAKF      24               0.3    1665

      Raw_Species            Target_Species       Strain
0    A. fumigatus     Aspergillus fumigatus          NaN
1    A. fumigatus     Aspergillus fumigatus          NaN
2  A. globiformis  Arthrobacter globiformis  VKM Ac-1112
3  A. globiformis  Arthrobacter globiformis  VKM Ac-1112
4  A. globiformis  Arthrobacter globiformis  VKM Ac-1112

已保存到 final_CAMP3_MIC_processed.csv